from __future__ import annotations

from typing import Any

from pydantable.expressions import ColumnRef, Expr, Literal, WhenChain

def abs(column: Expr) -> Expr: ...
def avg(column: Expr) -> Expr: ...
def between(column: Expr, lower: Any, upper: Any) -> Expr: ...
def binary_len(column: Expr) -> Expr: ...
def cast(column: Expr, dtype: Any) -> Expr: ...
def ceil(column: Expr) -> Expr: ...
def coalesce(*cols: Expr) -> Expr: ...
def col(name: str, *, dtype: Any | None = None) -> ColumnRef: ...
def column(name: str, *, dtype: Any | None = None) -> ColumnRef: ...
def concat(*cols: Expr) -> Expr: ...
def count(column: Expr | None = None) -> Expr: ...
def dayofmonth(column: Expr) -> Expr: ...
def day(column: Expr) -> Expr: ...
def dense_rank() -> Any: ...
def element_at(column: Expr, key: str) -> Expr: ...
def floor(column: Expr) -> Expr: ...
def hour(column: Expr) -> Expr: ...
def isin(column: Expr, *values: Any) -> Expr: ...
def isnotnull(column: Expr) -> Expr: ...
def isnull(column: Expr) -> Expr: ...
def lag(column: Expr, n: int = 1) -> Any: ...
def lead(column: Expr, n: int = 1) -> Any: ...
def length(column: Expr) -> Expr: ...
def list_contains(column: Expr, value: Any) -> Expr: ...
def list_get(column: Expr, index: Any) -> Expr: ...
def list_len(column: Expr) -> Expr: ...
def list_max(column: Expr) -> Expr: ...
def list_min(column: Expr) -> Expr: ...
def list_sum(column: Expr) -> Expr: ...
def lit(value: Any) -> Literal: ...
def lower(column: Expr) -> Expr: ...
def map_contains_key(column: Expr, key: str) -> Expr: ...
def map_entries(column: Expr) -> Expr: ...
def map_from_entries(column: Expr) -> Expr: ...
def map_get(column: Expr, key: str) -> Expr: ...
def map_keys(column: Expr) -> Expr: ...
def map_len(column: Expr) -> Expr: ...
def map_values(column: Expr) -> Expr: ...
def max(column: Expr) -> Expr: ...
def mean(column: Expr) -> Expr: ...
def min(column: Expr) -> Expr: ...
def minute(column: Expr) -> Expr: ...
def month(column: Expr) -> Expr: ...
def nanosecond(column: Expr) -> Expr: ...
def rank() -> Any: ...
def regexp_replace(column: Expr, pattern: str, replacement: str) -> Expr: ...
def row_number() -> Any: ...
def round(column: Expr, scale: int = 0) -> Expr: ...
def second(column: Expr) -> Expr: ...
def str_replace(column: Expr, pattern: str, replacement: str) -> Expr: ...
def strip_chars(column: Expr, chars: str) -> Expr: ...
def strip_prefix(column: Expr, prefix: str) -> Expr: ...
def strip_suffix(column: Expr, suffix: str) -> Expr: ...
def strptime(column: Expr, format: str, *, to_datetime: bool = True) -> Expr: ...
def substring(column: Expr, pos: Any, length: Any | None = None) -> Expr: ...
def sum(column: Expr) -> Expr: ...
def to_date(column: Expr, format: str | None = None) -> Expr: ...
def trim(column: Expr) -> Expr: ...
def upper(column: Expr) -> Expr: ...
def unix_timestamp(column: Expr, unit: str = "seconds") -> Expr: ...
def when(condition: Expr, value: Expr) -> WhenChain: ...
def window_avg(column: Expr) -> Any: ...
def window_max(column: Expr) -> Any: ...
def window_min(column: Expr) -> Any: ...
def window_sum(column: Expr) -> Any: ...
def year(column: Expr) -> Expr: ...

__all__ = [
    "abs",
    "avg",
    "between",
    "binary_len",
    "cast",
    "ceil",
    "coalesce",
    "col",
    "column",
    "concat",
    "count",
    "day",
    "dayofmonth",
    "dense_rank",
    "element_at",
    "floor",
    "hour",
    "isin",
    "isnotnull",
    "isnull",
    "lag",
    "lead",
    "length",
    "list_contains",
    "list_get",
    "list_len",
    "list_max",
    "list_min",
    "list_sum",
    "lit",
    "lower",
    "map_contains_key",
    "map_entries",
    "map_from_entries",
    "map_get",
    "map_keys",
    "map_len",
    "map_values",
    "max",
    "mean",
    "min",
    "minute",
    "month",
    "nanosecond",
    "rank",
    "regexp_replace",
    "round",
    "row_number",
    "second",
    "str_replace",
    "strip_chars",
    "strip_prefix",
    "strip_suffix",
    "strptime",
    "substring",
    "sum",
    "to_date",
    "trim",
    "unix_timestamp",
    "upper",
    "when",
    "window_avg",
    "window_max",
    "window_min",
    "window_sum",
    "year",
]
