from __future__ import annotations

from pydantable.mongo_beanie import sync_pymongo_collection
from pydantable.mongo_dataframe import (
    MongoDataFrame,
    MongoDataFrameModel,
    MongoPydantableEngine,
    MongoRoot,
)
from pydantable.spark_dataframe import SparkDataFrame, SparkDataFrameModel
from pydantable.sql_dataframe import SqlDataFrame, SqlDataFrameModel

from . import pandas as pandas
from . import plugins as plugins
from . import pyspark as pyspark
from . import selectors as selectors
from ._extension import MissingRustExtensionError
from .awaitable_dataframe_model import AwaitableDataFrameModel
from .dataframe import DataFrame
from .dataframe_model import DataFrameModel
from .display import get_repr_html_limits, reset_display_options, set_display_options
from .errors import ColumnLengthMismatchError, PydantableUserError
from .expressions import Expr
from .io import (
    BeanieWriteOptions,
    afetch_beanie,
    afetch_mongo,
    afetch_mongo_async,
    afetch_sql,
    afetch_sql_raw,
    afetch_sqlmodel,
    aiter_beanie,
    aiter_csv,
    aiter_ipc,
    aiter_json_array,
    aiter_json_lines,
    aiter_mongo,
    aiter_mongo_async,
    aiter_ndjson,
    aiter_parquet,
    aiter_sql,
    aiter_sql_raw,
    aiter_sqlmodel,
    amaterialize_json,
    amaterialize_parquet,
    aread_parquet,
    aread_parquet_url,
    awrite_beanie,
    awrite_mongo,
    awrite_mongo_async,
    awrite_sql_raw,
    awrite_sqlmodel,
    awrite_sqlmodel_batches,
    export_parquet,
    fetch_mongo,
    fetch_sql,
    fetch_sql_raw,
    fetch_sqlmodel,
    is_async_mongo_collection,
    iter_avro,
    iter_bigquery,
    iter_csv,
    iter_delta,
    iter_excel,
    iter_ipc,
    iter_json_array,
    iter_json_lines,
    iter_kafka_json,
    iter_mongo,
    iter_ndjson,
    iter_orc,
    iter_parquet,
    iter_snowflake,
    iter_sql_raw,
    iter_sqlmodel,
    materialize_ipc,
    materialize_json,
    materialize_ndjson,
    materialize_parquet,
    read_parquet,
    read_parquet_url,
    sqlmodel_columns,
    write_csv_batches,
    write_ipc_batches,
    write_mongo,
    write_ndjson_batches,
    write_parquet_batches,
    write_sql_raw,
    write_sqlmodel,
    write_sqlmodel_batches,
)
from .materialization import PlanMaterialization, plan_materialization_summary
from .observe import get_observer, set_observer
from .schema import DtypeDriftWarning, Schema
from .types import WKB

__version__ = "1.17.0"

__all__ = [
    "WKB",
    "AwaitableDataFrameModel",
    "BeanieWriteOptions",
    "ColumnLengthMismatchError",
    "DataFrame",
    "DataFrameModel",
    "DtypeDriftWarning",
    "Expr",
    "MissingRustExtensionError",
    "MongoDataFrame",
    "MongoDataFrameModel",
    "MongoPydantableEngine",
    "MongoRoot",
    "PlanMaterialization",
    "PydantableUserError",
    "Schema",
    "SparkDataFrame",
    "SparkDataFrameModel",
    "SqlDataFrame",
    "SqlDataFrameModel",
    "afetch_beanie",
    "afetch_mongo",
    "afetch_mongo_async",
    "afetch_sql",
    "afetch_sql_raw",
    "afetch_sqlmodel",
    "aiter_beanie",
    "aiter_csv",
    "aiter_ipc",
    "aiter_json_array",
    "aiter_json_lines",
    "aiter_mongo",
    "aiter_mongo_async",
    "aiter_ndjson",
    "aiter_parquet",
    "aiter_sql",
    "aiter_sql_raw",
    "aiter_sqlmodel",
    "amaterialize_json",
    "amaterialize_parquet",
    "aread_parquet",
    "aread_parquet_url",
    "awrite_beanie",
    "awrite_mongo",
    "awrite_mongo_async",
    "awrite_sql_raw",
    "awrite_sqlmodel",
    "awrite_sqlmodel_batches",
    "export_parquet",
    "fetch_mongo",
    "fetch_sql",
    "fetch_sql_raw",
    "fetch_sqlmodel",
    "get_observer",
    "get_repr_html_limits",
    "is_async_mongo_collection",
    "iter_avro",
    "iter_bigquery",
    "iter_csv",
    "iter_delta",
    "iter_excel",
    "iter_ipc",
    "iter_json_array",
    "iter_json_lines",
    "iter_kafka_json",
    "iter_mongo",
    "iter_ndjson",
    "iter_orc",
    "iter_parquet",
    "iter_snowflake",
    "iter_sql_raw",
    "iter_sqlmodel",
    "materialize_ipc",
    "materialize_json",
    "materialize_ndjson",
    "materialize_parquet",
    "pandas",
    "plan_materialization_summary",
    "plugins",
    "pyspark",
    "read_parquet",
    "read_parquet_url",
    "reset_display_options",
    "selectors",
    "set_display_options",
    "set_observer",
    "sqlmodel_columns",
    "sync_pymongo_collection",
    "write_csv_batches",
    "write_ipc_batches",
    "write_mongo",
    "write_ndjson_batches",
    "write_parquet_batches",
    "write_sql_raw",
    "write_sqlmodel",
    "write_sqlmodel_batches",
]
